# Generated by Django 5.2.17 on 2026-09-23 16:58

import common.validators
import django.db.models.deletion
import posts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True, max_length=2000)),
                ('image', models.ImageField(blank=True, null=True, upload_to=posts.models.post_upload_path, validators=[common.validators.validate_image])),
                ('location', models.CharField(blank=True, max_length=120)),
                ('moderation_status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('flagged', 'Flagged'), ('held', 'Held for review')], db_index=True, default='pending', max_length=16)),
                ('moderation_reason', models.TextField(blank=True, default='')),
                ('moderation_flags', models.JSONField(blank=True, default=list)),
                ('moderation_confidence', models.FloatField(blank=True, null=True)),
                ('moderation_checked_at', models.DateTimeField(blank=True, null=True)),
                ('moderation_provider', models.CharField(blank=True, default='', max_length=40)),
                ('is_hidden', models.BooleanField(default=False, help_text='Soft-deleted by the author.')),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['-created_at', 'is_hidden'], name='posts_post_created_475913_idx'), models.Index(fields=['author', '-created_at'], name='posts_post_author__f8ea20_idx'), models.Index(fields=['moderation_status'], name='posts_post_moderat_a129f8_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('content__gt', ''), ('image__isnull', False), _connector='OR'), name='post_requires_text_or_image')],
            },
        ),
    ]
