# Generated by Django 5.2.17 on 2026-09-24 06:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='post',
            name='post_requires_text_or_image',
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(condition=models.Q(('content__gt', ''), models.Q(('image__isnull', False), models.Q(('image', ''), _negated=True)), _connector='OR'), name='post_requires_text_or_image'),
        ),
    ]
