# Generated by Django 5.2.17 on 2026-09-23 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signal', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], db_index=True, max_length=10)),
                ('suggestion', models.TextField(blank=True, default='')),
                ('posts_analyzed', models.PositiveSmallIntegerField(default=0)),
                ('negative_streak', models.PositiveSmallIntegerField(default=0)),
                ('provider', models.CharField(blank=True, default='', max_length=40)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WellbeingNudge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('mood_check', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nudges', to='ai_companion.moodcheck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nudges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='moodcheck',
            index=models.Index(fields=['user', '-created_at'], name='ai_companio_user_id_899519_idx'),
        ),
        migrations.AddIndex(
            model_name='wellbeingnudge',
            index=models.Index(fields=['user', 'dismissed_at'], name='ai_companio_user_id_df40e6_idx'),
        ),
    ]
